# Generated by Django 2.2 on 2019-04-02 16:12

from django.db import migrations, models
import django.db.models.deletion
import utils.futils


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='admission_year',
            field=models.IntegerField(default=utils.futils.get_current_admission_year),
        ),
        migrations.AlterUniqueTogether(
            name='period',
            unique_together={('classroom', 'weekday', 'period_number', 'admission_year')},
        ),
        migrations.CreateModel(
            name='PeriodAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_removed', models.DateTimeField(blank=True, null=True)),
                ('adjusted_date', models.DateField()),
                ('adjusted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.SubjectTeacher')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.Period')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
