# Generated by Django 2.2 on 2019-04-04 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_auto_20190402_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_code',
            new_name='code',
        ),
    ]
