# Generated by Django 2.2 on 2019-04-04 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_auto_20190404_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='period',
            old_name='subject',
            new_name='subject_teacher',
        ),
    ]
