# Generated by Django 2.2 on 2019-05-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20190404_0651'),
        ('classrooms', '0005_auto_20190502_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('standard', 'division', 'school')},
        ),
    ]
