# Generated by Django 2.2 on 2019-04-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(default='DEFAULT', max_length=7, unique=True),
            preserve_default=False,
        ),
    ]
